/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_polyfx_jnphi_JNPhi */

#ifndef _Included_com_polyfx_jnphi_JNPhi
#define _Included_com_polyfx_jnphi_JNPhi
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     com_polyfx_jnphi_JNPhi
	* Method:    watch
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_com_polyfx_jnphi_JNPhi_watch
		(JNIEnv *, jobject);

	/*
	* Class:     com_polyfx_jnphi_JNPhi
	* Method:    zero
	* Signature: ()I
	*/
	JNIEXPORT jobject JNICALL Java_com_polyfx_jnphi_JNPhi_zero
		(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
